name: Pulumi Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - up
          - destroy

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

jobs:
  # Combined setup job
  setup-and-validate:
    name: Setup & Validate
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: Code Quality Checks
        run: |
          cd pulumi_project
          echo "🔍 Running code quality checks..."
          npx tsc --noEmit
          npx eslint . --ext .ts || echo "ESLint issues found"
          npm audit --audit-level high || echo "Security issues found"

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Initialize Pulumi Stack
        run: |
          cd pulumi_project
          echo "🔧 Setting up Pulumi..."
          pulumi login
          pulumi stack select dev || pulumi stack init dev
          pulumi config set aws:region ${{ env.AWS_REGION }}
          echo "✅ Stack ready!"

      - name: Validate Pulumi Code
        run: |
          cd pulumi_project
          pulumi validate

  # Preview job
  preview:
    name: Preview Infrastructure
    runs-on: ubuntu-latest
    needs: setup-and-validate
    if: github.event.inputs.action == 'preview'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-pulumi # Create reusable action
        
      - name: Preview Infrastructure
        run: |
          cd pulumi_project
          echo "🔍 Generating infrastructure preview..."
          pulumi preview --stack dev --diff --show-replacement-steps
          
      - name: Generate Dashboard Links
        run: |
          cd pulumi_project
          echo "🔗 Pulumi Dashboard:"
          echo "https://app.pulumi.com/$(pulumi whoami)/pulumi-project/dev"

  # Deploy job  
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: setup-and-validate
    if: github.event.inputs.action == 'up'
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-pulumi
        
      - name: Deploy Infrastructure
        run: |
          cd pulumi_project
          echo "🚀 Deploying infrastructure..."
          pulumi up --yes --stack dev

  # Destroy job
  destroy:
    name: Destroy Infrastructure  
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-pulumi
        
      - name: Destroy Infrastructure
        run: |
          cd pulumi_project
          echo "🗑️ Destroying infrastructure..."
          pulumi destroy --yes --stack dev