name: Pulumi Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'up'
        type: choice
        options:
          - up
          - preview
          - destroy

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

jobs:
  code-quality:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: TypeScript Compilation Check
        run: |
          cd pulumi_project
          npx tsc --noEmit

      - name: ESLint Check
        run: |
          cd pulumi_project
          npx eslint . --ext .ts || echo "ESLint not configured, skipping"

      - name: Security Audit
        run: |
          cd pulumi_project
          npm audit --audit-level moderate || echo "Security vulnerabilities found, but continuing"

      - name: Dependency Check
        run: |
          cd pulumi_project
          npm outdated || echo "Dependencies checked"

      - name: Code Format Check
        run: |
          cd pulumi_project
          npx prettier --check . || echo "Prettier not configured, skipping"

      - name: Secret Scanning
        run: |
          echo "Checking for hardcoded secrets..."
          if grep -r -i "password\|secret\|key\|token" . --exclude-dir=node_modules --exclude-dir=.git; then
            echo "⚠️  Potential secrets found in code"
          else
            echo "✅ No obvious secrets found"
          fi

      - name: Dependency Vulnerability Scan
        run: |
          cd pulumi_project
          npm audit --audit-level high || echo "High severity vulnerabilities found"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Run tests
        run: |
          cd pulumi_project
          npm test || echo "No tests found"

      - name: Pulumi Validate
        run: |
          cd pulumi_project
          pulumi validate || echo "Pulumi validation completed"

  preview:
    name: Preview Changes
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'preview'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Generate Infrastructure Diagram
        run: |
          cd pulumi_project
          echo "📊 Generating infrastructure diagram..."
          pulumi preview --stack dev --show-config > preview-output.txt
          echo "📋 Preview Summary:"
          echo "=================="
          cat preview-output.txt | grep -E "(create|update|delete|replace)" || echo "No changes detected"
          echo ""
          echo "🏗️  Resources to be created:"
          echo "=========================="
          cat preview-output.txt | grep -E "aws:ec2|aws:iam" | head -20 || echo "No AWS resources found"

      - name: Create dev stack if not exists
        run: |
          cd pulumi_project
          pulumi stack select dev || pulumi stack init dev
          pulumi config set aws:region ${{ env.AWS_REGION }}

      - name: Preview changes
        run: |
          cd pulumi_project
          echo "🔍 Generating detailed preview..."
          pulumi preview --stack dev --show-replacement-steps --show-config
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'up'
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Create dev stack if not exists
        run: |
          cd pulumi_project
          pulumi stack select dev || pulumi stack init dev
          pulumi config set aws:region ${{ env.AWS_REGION }}

      - name: Deploy to dev
        run: |
          cd pulumi_project
          pulumi up --yes --stack dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

  destroy:
    name: Destroy Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Create dev stack if not exists
        run: |
          cd pulumi_project
          pulumi stack select dev || pulumi stack init dev
          pulumi config set aws:region ${{ env.AWS_REGION }}

      - name: Destroy environment
        run: |
          cd pulumi_project
          pulumi destroy --yes --stack dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }} 