name: Pulumi Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'up'
        type: choice
        options:
          - up
          - preview
          - destroy

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Run tests
        run: |
          cd pulumi_project
          npm test || echo "No tests found"

  preview:
    name: Preview Changes
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'preview') || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Create dev stack if not exists
        run: |
          cd pulumi_project
          pulumi stack select dev || pulumi stack init dev
          pulumi config set aws:region ${{ env.AWS_REGION }}

      - name: Preview changes
        run: |
          cd pulumi_project
          pulumi preview --stack dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: test
    if: (github.ref == 'refs/heads/develop' && github.event_name == 'push') || (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'up')
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Create dev stack if not exists
        run: |
          cd pulumi_project
          pulumi stack select dev || pulumi stack init dev
          pulumi config set aws:region ${{ env.AWS_REGION }}

      - name: Deploy to dev
        run: |
          cd pulumi_project
          pulumi up --yes --stack dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}



  destroy:
    name: Destroy Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd pulumi_project
          npm install

      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Create dev stack if not exists
        run: |
          cd pulumi_project
          pulumi stack select dev || pulumi stack init dev
          pulumi config set aws:region ${{ env.AWS_REGION }}

      - name: Destroy environment
        run: |
          cd pulumi_project
          pulumi destroy --yes --stack dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }} 